//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloDTO", Namespace="http://ventasservice.org/")]
    [System.SerializableAttribute()]
    public partial class ArticuloDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private decimal PrecioVentaField;
        
        private decimal PrecioCompraField;
        
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDTO", Namespace="http://ventasservice.org/")]
    [System.SerializableAttribute()]
    public partial class ClienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentasCabeceraDTO", Namespace="http://ventasservice.org/")]
    [System.SerializableAttribute()]
    public partial class VentasCabeceraDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        private int IdClienteField;
        
        private int IdVendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdVendedor {
            get {
                return this.IdVendedorField;
            }
            set {
                if ((this.IdVendedorField.Equals(value) != true)) {
                    this.IdVendedorField = value;
                    this.RaisePropertyChanged("IdVendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentasDetalleDTO", Namespace="http://ventasservice.org/")]
    [System.SerializableAttribute()]
    public partial class VentasDetalleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int IdVentaCabeceraField;
        
        private int IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecioUnitarioField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVentaCabecera {
            get {
                return this.IdVentaCabeceraField;
            }
            set {
                if ((this.IdVentaCabeceraField.Equals(value) != true)) {
                    this.IdVentaCabeceraField = value;
                    this.RaisePropertyChanged("IdVentaCabecera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecioUnitarioField, value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ventasservice.org/", ConfigurationName="Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/HelloWorld", ReplyAction="*")]
        ECommerce.Service.HelloWorldResponse HelloWorld(ECommerce.Service.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetArticulosResult del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/GetArticulos", ReplyAction="*")]
        ECommerce.Service.GetArticulosResponse GetArticulos(ECommerce.Service.GetArticulosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Login", ReplyAction="*")]
        ECommerce.Service.LoginResponse Login(ECommerce.Service.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Registrarse", ReplyAction="*")]
        ECommerce.Service.RegistrarseResponse Registrarse(ECommerce.Service.RegistrarseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/GetArticulosByNombre", ReplyAction="*")]
        ECommerce.Service.GetArticulosByNombreResponse GetArticulosByNombre(ECommerce.Service.GetArticulosByNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ArticuloForCarritoResult del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/ArticuloForCarrito", ReplyAction="*")]
        ECommerce.Service.ArticuloForCarritoResponse ArticuloForCarrito(ECommerce.Service.ArticuloForCarritoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Cabecera", ReplyAction="*")]
        ECommerce.Service.CabeceraResponse Cabecera(ECommerce.Service.CabeceraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento precioventa del espacio de nombres http://ventasservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Detalle", ReplyAction="*")]
        ECommerce.Service.DetalleResponse Detalle(ECommerce.Service.DetalleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ECommerce.Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ECommerce.Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticulos", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.GetArticulosRequestBody Body;
        
        public GetArticulosRequest() {
        }
        
        public GetArticulosRequest(ECommerce.Service.GetArticulosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetArticulosRequestBody {
        
        public GetArticulosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticulosResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.GetArticulosResponseBody Body;
        
        public GetArticulosResponse() {
        }
        
        public GetArticulosResponse(ECommerce.Service.GetArticulosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class GetArticulosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.ArticuloDTO[] GetArticulosResult;
        
        public GetArticulosResponseBody() {
        }
        
        public GetArticulosResponseBody(ECommerce.Service.ArticuloDTO[] GetArticulosResult) {
            this.GetArticulosResult = GetArticulosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ECommerce.Service.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ECommerce.Service.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.ClienteDTO LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(ECommerce.Service.ClienteDTO LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registrarse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.RegistrarseRequestBody Body;
        
        public RegistrarseRequest() {
        }
        
        public RegistrarseRequest(ECommerce.Service.RegistrarseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class RegistrarseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string contraseña;
        
        public RegistrarseRequestBody() {
        }
        
        public RegistrarseRequestBody(string nombre, string direccion, string telefono, string email, string usuario, string contraseña) {
            this.nombre = nombre;
            this.direccion = direccion;
            this.telefono = telefono;
            this.email = email;
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarseResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.RegistrarseResponseBody Body;
        
        public RegistrarseResponse() {
        }
        
        public RegistrarseResponse(ECommerce.Service.RegistrarseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class RegistrarseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.ClienteDTO RegistrarseResult;
        
        public RegistrarseResponseBody() {
        }
        
        public RegistrarseResponseBody(ECommerce.Service.ClienteDTO RegistrarseResult) {
            this.RegistrarseResult = RegistrarseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticulosByNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticulosByNombre", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.GetArticulosByNombreRequestBody Body;
        
        public GetArticulosByNombreRequest() {
        }
        
        public GetArticulosByNombreRequest(ECommerce.Service.GetArticulosByNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class GetArticulosByNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public GetArticulosByNombreRequestBody() {
        }
        
        public GetArticulosByNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArticulosByNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArticulosByNombreResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.GetArticulosByNombreResponseBody Body;
        
        public GetArticulosByNombreResponse() {
        }
        
        public GetArticulosByNombreResponse(ECommerce.Service.GetArticulosByNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class GetArticulosByNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.ArticuloDTO[] GetArticulosByNombreResult;
        
        public GetArticulosByNombreResponseBody() {
        }
        
        public GetArticulosByNombreResponseBody(ECommerce.Service.ArticuloDTO[] GetArticulosByNombreResult) {
            this.GetArticulosByNombreResult = GetArticulosByNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArticuloForCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ArticuloForCarrito", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.ArticuloForCarritoRequestBody Body;
        
        public ArticuloForCarritoRequest() {
        }
        
        public ArticuloForCarritoRequest(ECommerce.Service.ArticuloForCarritoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class ArticuloForCarritoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ArticuloForCarritoRequestBody() {
        }
        
        public ArticuloForCarritoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArticuloForCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ArticuloForCarritoResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.ArticuloForCarritoResponseBody Body;
        
        public ArticuloForCarritoResponse() {
        }
        
        public ArticuloForCarritoResponse(ECommerce.Service.ArticuloForCarritoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class ArticuloForCarritoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.ArticuloDTO ArticuloForCarritoResult;
        
        public ArticuloForCarritoResponseBody() {
        }
        
        public ArticuloForCarritoResponseBody(ECommerce.Service.ArticuloDTO ArticuloForCarritoResult) {
            this.ArticuloForCarritoResult = ArticuloForCarritoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CabeceraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cabecera", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.CabeceraRequestBody Body;
        
        public CabeceraRequest() {
        }
        
        public CabeceraRequest(ECommerce.Service.CabeceraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class CabeceraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha;
        
        public CabeceraRequestBody() {
        }
        
        public CabeceraRequestBody(int idCliente, string fecha) {
            this.idCliente = idCliente;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CabeceraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CabeceraResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.CabeceraResponseBody Body;
        
        public CabeceraResponse() {
        }
        
        public CabeceraResponse(ECommerce.Service.CabeceraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class CabeceraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.VentasCabeceraDTO CabeceraResult;
        
        public CabeceraResponseBody() {
        }
        
        public CabeceraResponseBody(ECommerce.Service.VentasCabeceraDTO CabeceraResult) {
            this.CabeceraResult = CabeceraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Detalle", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.DetalleRequestBody Body;
        
        public DetalleRequest() {
        }
        
        public DetalleRequest(ECommerce.Service.DetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class DetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idcabecera;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idarticulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string precioventa;
        
        public DetalleRequestBody() {
        }
        
        public DetalleRequestBody(int idcabecera, int idarticulo, string precioventa) {
            this.idcabecera = idcabecera;
            this.idarticulo = idarticulo;
            this.precioventa = precioventa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetalleResponse", Namespace="http://ventasservice.org/", Order=0)]
        public ECommerce.Service.DetalleResponseBody Body;
        
        public DetalleResponse() {
        }
        
        public DetalleResponse(ECommerce.Service.DetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ventasservice.org/")]
    public partial class DetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECommerce.Service.VentasDetalleDTO DetalleResult;
        
        public DetalleResponseBody() {
        }
        
        public DetalleResponseBody(ECommerce.Service.VentasDetalleDTO DetalleResult) {
            this.DetalleResult = DetalleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ECommerce.Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ECommerce.Service.ServiceSoap>, ECommerce.Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.HelloWorldResponse ECommerce.Service.ServiceSoap.HelloWorld(ECommerce.Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ECommerce.Service.HelloWorldRequest inValue = new ECommerce.Service.HelloWorldRequest();
            inValue.Body = new ECommerce.Service.HelloWorldRequestBody();
            ECommerce.Service.HelloWorldResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.GetArticulosResponse ECommerce.Service.ServiceSoap.GetArticulos(ECommerce.Service.GetArticulosRequest request) {
            return base.Channel.GetArticulos(request);
        }
        
        public ECommerce.Service.ArticuloDTO[] GetArticulos() {
            ECommerce.Service.GetArticulosRequest inValue = new ECommerce.Service.GetArticulosRequest();
            inValue.Body = new ECommerce.Service.GetArticulosRequestBody();
            ECommerce.Service.GetArticulosResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).GetArticulos(inValue);
            return retVal.Body.GetArticulosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.LoginResponse ECommerce.Service.ServiceSoap.Login(ECommerce.Service.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ECommerce.Service.ClienteDTO Login(string usuario, string contraseña) {
            ECommerce.Service.LoginRequest inValue = new ECommerce.Service.LoginRequest();
            inValue.Body = new ECommerce.Service.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            ECommerce.Service.LoginResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.RegistrarseResponse ECommerce.Service.ServiceSoap.Registrarse(ECommerce.Service.RegistrarseRequest request) {
            return base.Channel.Registrarse(request);
        }
        
        public ECommerce.Service.ClienteDTO Registrarse(string nombre, string direccion, string telefono, string email, string usuario, string contraseña) {
            ECommerce.Service.RegistrarseRequest inValue = new ECommerce.Service.RegistrarseRequest();
            inValue.Body = new ECommerce.Service.RegistrarseRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            inValue.Body.telefono = telefono;
            inValue.Body.email = email;
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            ECommerce.Service.RegistrarseResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).Registrarse(inValue);
            return retVal.Body.RegistrarseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.GetArticulosByNombreResponse ECommerce.Service.ServiceSoap.GetArticulosByNombre(ECommerce.Service.GetArticulosByNombreRequest request) {
            return base.Channel.GetArticulosByNombre(request);
        }
        
        public ECommerce.Service.ArticuloDTO[] GetArticulosByNombre(string nombre) {
            ECommerce.Service.GetArticulosByNombreRequest inValue = new ECommerce.Service.GetArticulosByNombreRequest();
            inValue.Body = new ECommerce.Service.GetArticulosByNombreRequestBody();
            inValue.Body.nombre = nombre;
            ECommerce.Service.GetArticulosByNombreResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).GetArticulosByNombre(inValue);
            return retVal.Body.GetArticulosByNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.ArticuloForCarritoResponse ECommerce.Service.ServiceSoap.ArticuloForCarrito(ECommerce.Service.ArticuloForCarritoRequest request) {
            return base.Channel.ArticuloForCarrito(request);
        }
        
        public ECommerce.Service.ArticuloDTO ArticuloForCarrito(int id) {
            ECommerce.Service.ArticuloForCarritoRequest inValue = new ECommerce.Service.ArticuloForCarritoRequest();
            inValue.Body = new ECommerce.Service.ArticuloForCarritoRequestBody();
            inValue.Body.id = id;
            ECommerce.Service.ArticuloForCarritoResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).ArticuloForCarrito(inValue);
            return retVal.Body.ArticuloForCarritoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.CabeceraResponse ECommerce.Service.ServiceSoap.Cabecera(ECommerce.Service.CabeceraRequest request) {
            return base.Channel.Cabecera(request);
        }
        
        public ECommerce.Service.VentasCabeceraDTO Cabecera(int idCliente, string fecha) {
            ECommerce.Service.CabeceraRequest inValue = new ECommerce.Service.CabeceraRequest();
            inValue.Body = new ECommerce.Service.CabeceraRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.fecha = fecha;
            ECommerce.Service.CabeceraResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).Cabecera(inValue);
            return retVal.Body.CabeceraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.Service.DetalleResponse ECommerce.Service.ServiceSoap.Detalle(ECommerce.Service.DetalleRequest request) {
            return base.Channel.Detalle(request);
        }
        
        public ECommerce.Service.VentasDetalleDTO Detalle(int idcabecera, int idarticulo, string precioventa) {
            ECommerce.Service.DetalleRequest inValue = new ECommerce.Service.DetalleRequest();
            inValue.Body = new ECommerce.Service.DetalleRequestBody();
            inValue.Body.idcabecera = idcabecera;
            inValue.Body.idarticulo = idarticulo;
            inValue.Body.precioventa = precioventa;
            ECommerce.Service.DetalleResponse retVal = ((ECommerce.Service.ServiceSoap)(this)).Detalle(inValue);
            return retVal.Body.DetalleResult;
        }
    }
}
